name: Feature Request
description: File a feature request for Pad.
title: "[Feature] <title>"
labels: [enhancement]
assignees:
  - hickatheworld
body:
  - type: markdown
    attributes:
      value: |
        **This form is for *Feature Requests* only, not Bug Reports!**
        **If you know how to implement this and want to do it yourself, please file a Pull Request instead!**
  - type: checkboxes
  attributes:
    label: Is there an existing issue/PR for this?
    description: Please search to see if an issue/PR already exists for the feature you are requesting.
    options:
    - label: I have searched the existing issues
      required: true
  - type: dropdown
    id: field
    attributes:
      label: Scope
      description: What part of the app this feature about ? 
      options:
        - Installer
        - Audio
        - UI
        - Other (specify in next input)
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: What feature do you want to see in  Pad?
      placeholder: A cookie recipee.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Is this feature related to specific OS only?
      description: If not, skip this.
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux